CREATE TABLE IF NOT EXISTS health_metric (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  measure_date DATE NOT NULL,
  steps INT,
  resting_heart_rate INT,
  sleep_hours DECIMAL(4, 2),
  systolic INT,
  diastolic INT,
  stress_level INT,
  source_id BIGINT,
  source_type VARCHAR(32) NOT NULL DEFAULT 'manual',
  source_name VARCHAR(64),
  sync_task_id BIGINT,
  created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_change_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_metric_user_date (user_id, measure_date),
  KEY idx_metric_date (measure_date),
  KEY idx_metric_source (source_id),
  KEY idx_metric_sync_task (sync_task_id),
  CONSTRAINT fk_metric_user FOREIGN KEY (user_id) REFERENCES t_user(user_id),
  CONSTRAINT fk_metric_source FOREIGN KEY (source_id) REFERENCES t_data_source(source_id) ON DELETE SET NULL,
  CONSTRAINT fk_metric_sync_task FOREIGN KEY (sync_task_id) REFERENCES t_sync_task(task_id) ON DELETE SET NULL
);
